# Generated by Django 3.1.7 on 2021-07-23 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('address_2', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('zip', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vat', models.DecimalField(decimal_places=2, default=8.0, max_digits=7)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('check_in', models.CharField(max_length=10)),
                ('check_out', models.CharField(max_length=10)),
                ('payed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=64)),
                ('bed_type', models.CharField(max_length=64)),
                ('max_people', models.IntegerField()),
                ('accommodates', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('view', models.CharField(max_length=32)),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('child_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('weekly_discount', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_main', models.URLField(max_length=500)),
                ('image_1', models.URLField(max_length=500)),
                ('image_2', models.URLField(max_length=500)),
                ('image_3', models.URLField(max_length=500)),
                ('image_4', models.URLField(max_length=500)),
                ('image_5', models.URLField(max_length=500)),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asgard.rooms')),
            ],
        ),
    ]
