# Generated by Django 3.1.7 on 2021-07-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asgard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media'},
        ),
    ]
