# Generated by Django 3.1.7 on 2021-07-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard', '0003_auto_20210723_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image_1',
            field=models.CharField(default='-', max_length=256),
        ),
        migrations.AlterField(
            model_name='media',
            name='image_2',
            field=models.CharField(default='-', max_length=256),
        ),
        migrations.AlterField(
            model_name='media',
            name='image_3',
            field=models.CharField(default='-', max_length=256),
        ),
        migrations.AlterField(
            model_name='media',
            name='image_4',
            field=models.CharField(default='-', max_length=256),
        ),
        migrations.AlterField(
            model_name='media',
            name='image_5',
            field=models.CharField(default='-', max_length=256),
        ),
        migrations.AlterField(
            model_name='media',
            name='image_main',
            field=models.CharField(default='-', max_length=256),
        ),
    ]
