# Generated by Django 3.1.7 on 2021-07-23 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asgard', '0004_auto_20210723_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='asgard.rooms'),
        ),
    ]
