# Generated by Django 3.1.7 on 2021-07-24 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asgard', '0007_rooms_url_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='zip',
            new_name='zipcode',
        ),
        migrations.AddField(
            model_name='reservations',
            name='reserved_room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='asgard.rooms'),
            preserve_default=False,
        ),
    ]
