# Generated by Django 3.1.7 on 2021-07-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard', '0009_auto_20210724_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='address_2',
            field=models.CharField(default='-', max_length=64),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='adult',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='child',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
