# Generated by Django 3.1.7 on 2021-07-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard', '0011_reservations_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
    ]
