# Generated by Django 3.1.7 on 2021-07-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard', '0012_auto_20210725_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='check_out',
            field=models.DateField(null=True),
        ),
    ]
