# Generated by Django 3.1.7 on 2021-07-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asgard', '0013_auto_20210725_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='room_name',
        ),
    ]
