# Generated by Django 3.1.7 on 2021-07-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard', '0014_remove_reservations_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='room_name',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
