# Generated by Django 3.1.7 on 2021-07-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asgard', '0015_reservations_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='room_name',
        ),
    ]
